# SPDX-License-Identifier: AGPL-3.0-or-later
[Service]
MemoryDenyWriteExecute=yes
RestrictAddressFamilies=AF_UNIX AF_NETLINK
SystemCallFilter=@system-service @mount
CapabilityBoundingSet=CAP_SYS_ADMIN CAP_SYS_RAWIO
