# SPDX-License-Identifier: AGPL-3.0-or-later
[Service]
ProtectSystem=strict
ProtectHome=yes
ReadWritePaths=/etc/NetworkManager /var/lib/NetworkManager -/run/NetworkManager
ProtectKernelLogs=yes
ProtectControlGroups=yes
ProtectClock=yes
ProtectProc=invisible
PrivateTmp=yes
PrivateDevices=yes
RestrictAddressFamilies=AF_INET AF_INET6 AF_NETLINK AF_PACKET AF_UNIX
RestrictNamespaces=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
LockPersonality=yes
SystemCallArchitectures=native
UMask=0027
