# SPDX-License-Identifier: AGPL-3.0-or-later
# shellcheck shell=sh
#
# Target: /etc/profile.d/aide-alert.sh  (sourced, deliberately no shebang)
#
# Surfaces the aggregate integrity-check result as a banner on interactive
# shell start. Silent when the check exited 0; banner on 1 (findings) or
# 2 (tool failure).
#
# Reads integrity-check.service, not aide-check.service: AIDE is one of four
# checks and runs nested under the outer unit. The outer unit's status is the
# aggregate one.
#
# No bitmask decoding. AIDE's 1/2/4 encoding describes one tool's three change
# classes and does not extend to four aggregated checks; carrying it forward
# would be wrong rather than merely imprecise. Which check fired is in the log.
#
# Mode 0644 root:root. Sourced by the /etc/profile loop on login shells.

# Skip non-interactive shells (cron, scp, sftp).
case $- in *i*) ;; *) return 0 ;; esac

# Last invocation exit status. Empty (never ran) or 0 (clean) -> silent.
_ic_rc=$(systemctl show -p ExecMainStatus --value integrity-check.service 2>/dev/null)
case "$_ic_rc" in 0|"") unset _ic_rc; return 0 ;; esac

_ic_ts=$(systemctl show -p ExecMainExitTimestamp --value integrity-check.service 2>/dev/null)

# Run identity plus acknowledgement: silent when this run was already
# acknowledged. Keyed on the monotonic exit timestamp so a reviewed finding
# stops re-announcing itself without suppressing the next, distinct run. The
# acknowledgement file lives in the per-boot runtime directory and therefore
# expires at reboot by construction.
_ic_mono=$(systemctl show -p ExecMainExitTimestampMonotonic --value integrity-check.service 2>/dev/null)
_ic_ack="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/aide-alert.ack"
if [ -n "$_ic_mono" ] && [ -f "$_ic_ack" ] && \
   [ "$(cat "$_ic_ack" 2>/dev/null)" = "$_ic_mono" ]; then
    unset _ic_rc _ic_ts _ic_mono _ic_ack ; return 0
fi

case "$_ic_rc" in
    1) _ic_what="findings -- at least one check reports deviations" ;;
    2) _ic_what="tool failure -- at least one check did not complete" ;;
    *) _ic_what="unexpected exit status $_ic_rc" ;;
esac

# SC2012 disabled on purpose: this runs on EVERY interactive login. `ls -1t`
# piped to `head` is one process; a find/-printf/sort pipeline would be three.
# The file names are generated by integrity-check from a timestamp and a
# transaction id, so no special characters are possible.
# shellcheck disable=SC2012
_ic_log=$(ls -1t /var/log/aide/integrity-*.log 2>/dev/null | head -1)

printf '\n  \033[1;33m! Integrity check:\033[0m %s\n' "$_ic_what"
printf '    Last run: %s\n' "${_ic_ts:-?}"
printf '    Log:      %s\n' "${_ic_log:-/var/log/aide/integrity-*.log}"
printf '    Review:   sudo -r sysadm_r -t sysadm_t cat <log>\n'
printf '    Accept:   sudo /usr/local/sbin/integrity-check accept   (only after review)\n\n'

unset _ic_rc _ic_ts _ic_mono _ic_ack _ic_what _ic_log
