# SPDX-License-Identifier: AGPL-3.0-or-later
[Service]
ProtectClock=yes
ProtectKernelLogs=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
SystemCallArchitectures=native
MemoryDenyWriteExecute=yes
